# Generated by Django 3.2.3 on 2021-09-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dotaciones',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=50)),
                ('sistema_operativo', models.CharField(max_length=40)),
                ('fecha_asignado', models.DateField()),
                ('empleado_asignado', models.CharField(max_length=60)),
                ('empleado_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
