# Generated by Django 3.2.3 on 2021-09-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210913_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotaciones',
            name='fecha_asignado',
            field=models.DateField(blank=True),
        ),
    ]
