# Generated by Django 3.2.3 on 2021-09-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dotaciones_fecha_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotaciones',
            name='fecha_asignado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
